# Botón "Sponsor" del repositorio. https://docs.github.com/es/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
ko_fi: fjmarlop
